name: Build container image

on:
  workflow_dispatch:
  push:
    branches:
      - 'sinoru/main'
      - 'sinoru/develop'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+\+sinoru*'
    paths:
      - .github/workflows/build-image.yml
      - Dockerfile
      - src/**.c
  pull_request:
    paths:
      - .github/workflows/build-image.yml
      - Dockerfile
      - src/**.c

permissions:
  contents: read
  packages: write

env:
  DOCKER_IMAGE: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker-platforms: ['linux/amd64', 'linux/arm64']

    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.docker-platforms }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          cache-from: type=gha,scope=$GITHUB_REF_NAME/${{ matrix.docker-platforms }}
          cache-to: type=gha,scope=$GITHUB_REF_NAME/${{ matrix.docker-platforms }},mode=max
          outputs: type=image,name=${{ env.DOCKER_IMAGE }},push-by-digest=${{ github.event_name != 'pull_request' }},name-canonical=true,push=${{ github.event_name != 'pull_request' }}
      - name: Export digest
        run: |
          export DIGESTS_PATH="$RUNNER_TEMP/$(uuidgen)/digests"
          echo "DIGESTS_PATH=$DIGESTS_PATH" >>${GITHUB_ENV}
          mkdir -p $DIGESTS_PATH
          digest="${{ steps.build.outputs.digest }}"
          touch "$DIGESTS_PATH/${digest#sha256:}"
      - name: Upload digest
        uses: actions/upload-artifact@v3
        with:
          name: digests
          path: ${{ env.DIGESTS_PATH }}/*
          if-no-files-found: error
          retention-days: 1

  mix:
    if: github.event_name != 'pull_request'
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Create DIGESTS_PATH
        run: |
          export DIGESTS_PATH="$RUNNER_TEMP/$(uuidgen)/digests"
          echo "DIGESTS_PATH=$DIGESTS_PATH" >>${GITHUB_ENV}
      - name: Download digests
        uses: actions/download-artifact@v3
        with:
          name: digests
          path: ${{ env.DIGESTS_PATH }}
      - uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - run: echo "DOCKER_IMAGE=${DOCKER_IMAGE,,}" >>${GITHUB_ENV} # repository name must be lowercase
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ env.DOCKER_IMAGE }}
          flavor: |
            latest=auto
          tags: |
            type=edge,branch=musubi.moe/main
            type=edge,branch=musubi.moe/develop
            type=semver,pattern={{raw}}
            type=ref,event=pr
      - name: Create manifest list and push
        working-directory: ${{ env.DIGESTS_PATH }}
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.DOCKER_IMAGE }}@sha256:%s ' *)
      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.DOCKER_IMAGE }}:${{ steps.meta.outputs.version }}
